#!/bin/bash
# Sets up infra + cluster add-ons via Terraform, then registers the app
# with ArgoCD. Usage: ./create.sh [--infra-only]

set -e

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TERRAFORM_DIR="$PROJECT_DIR/terraform"
ARGOCD_APP="$PROJECT_DIR/gitops/argocd-application.yaml"

# Load secrets from .env if present (gitignored - see .env.example for what's needed).
if [ -f "$PROJECT_DIR/.env" ]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

INFRA_ONLY=false
if [ "$1" == "--infra-only" ]; then
    INFRA_ONLY=true
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_header() {
    echo -e "\n${GREEN}╔════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║ $1${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}\n"
}

print_step() {
    echo -e "${YELLOW}▶ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

check_prerequisites() {
    print_header "CHECKING PREREQUISITES"

    local missing_tools=0

    if ! command -v terraform &> /dev/null; then
        print_error "Terraform not installed"
        missing_tools=$((missing_tools + 1))
    else
        print_success "Terraform: $(terraform --version | head -1)"
    fi

    if ! command -v aws &> /dev/null; then
        print_error "AWS CLI not installed"
        missing_tools=$((missing_tools + 1))
    else
        print_success "AWS CLI: $(aws --version | head -1)"
    fi

    if ! command -v kubectl &> /dev/null; then
        print_error "kubectl not installed"
        missing_tools=$((missing_tools + 1))
    else
        print_success "kubectl: $(kubectl version --client --short 2>/dev/null || echo 'installed')"
    fi

    if ! command -v docker &> /dev/null; then
        print_error "Docker not installed"
        missing_tools=$((missing_tools + 1))
    else
        print_success "Docker: $(docker --version)"
    fi

    # jq parses the GitHub API responses in configure_github_webhook.
    if ! command -v jq &> /dev/null; then
        print_error "jq not installed"
        missing_tools=$((missing_tools + 1))
    else
        print_success "jq: $(jq --version)"
    fi

    if [ $missing_tools -gt 0 ]; then
        print_error "$missing_tools tools missing. Please install them first."
        exit 1
    fi

    if ! aws sts get-caller-identity &> /dev/null; then
        print_error "AWS credentials not configured. Run: aws configure"
        exit 1
    fi
    print_success "AWS credentials configured"

    # The only project secret a human supplies (AWS credentials are checked
    # above): Grafana's and Jenkins' passwords are generated by Terraform,
    # and the database password by AWS.
    if [ -z "$TF_VAR_github_pat" ]; then
        print_error "TF_VAR_github_pat is not set."
        print_error "Needs 'repo' and 'admin:repo_hook' scopes: https://github.com/settings/tokens"
        print_error "Copy .env.example to .env, fill it in, and re-run (or export it directly)."
        exit 1
    fi

    # A wrong, expired or scope-less PAT would otherwise surface ~25 minutes
    # later as a silently broken webhook and a Jenkins job that cannot clone,
    # so it is checked against the API here instead.
    local pat_headers pat_status pat_scopes
    pat_headers=$(mktemp)
    pat_status=$(curl -s -o /dev/null -D "$pat_headers" -w '%{http_code}'         -H "Authorization: token $TF_VAR_github_pat"         -H "X-GitHub-Api-Version: 2022-11-28"         https://api.github.com/user || echo "000")

    if [ "$pat_status" != "200" ]; then
        rm -f "$pat_headers"
        print_error "GitHub rejected TF_VAR_github_pat (HTTP $pat_status)."
        print_error "Paste the token itself (ghp_... or github_pat_...), not the URL of the token page."
        print_error "Create one at https://github.com/settings/tokens with 'repo' + 'admin:repo_hook'."
        exit 1
    fi

    # Classic tokens report their scopes in this header; fine-grained ones leave
    # it empty, so treat a missing scope there as a warning rather than a stop.
    pat_scopes=$(grep -i '^x-oauth-scopes:' "$pat_headers" | cut -d: -f2- | tr -d ' \015' || true)
    rm -f "$pat_headers"

    if [ -n "$pat_scopes" ]; then
        case ",$pat_scopes," in
            *,repo,*) ;;
            *)
                print_error "The PAT works but is missing the 'repo' scope (has: $pat_scopes)."
                print_error "Jenkins cannot clone the repo or push the image-tag bump without it."
                exit 1
                ;;
        esac
        case ",$pat_scopes," in
            *,admin:repo_hook,*|*,write:repo_hook,*) ;;
            *) echo -e "${YELLOW}WARNING: PAT has no admin:repo_hook scope - webhook setup may fail (has: $pat_scopes)${NC}" ;;
        esac
    fi

    print_success "GitHub PAT is valid${pat_scopes:+ (scopes: $pat_scopes)}"

    # The Jenkins security group opens 8080 to this address and to GitHub's
    # webhook ranges, nothing else. Detected rather than hardcoded, so a
    # changing home IP does not quietly lock the UI out on the next run.
    if [ -z "$TF_VAR_jenkins_ui_allowed_cidrs" ]; then
        local my_ip
        my_ip=$(curl -s --max-time 10 https://checkip.amazonaws.com | tr -d '[:space:]' || true)
        if echo "$my_ip" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
            export TF_VAR_jenkins_ui_allowed_cidrs="[\"$my_ip/32\"]"
            print_success "Jenkins UI will be reachable from $my_ip/32 only"
        else
            echo -e "${YELLOW}WARNING: could not detect this machine's public IP - the Jenkins UI will not be reachable.${NC}"
            echo -e "${YELLOW}Set TF_VAR_jenkins_ui_allowed_cidrs='[\"x.x.x.x/32\"]' to override.${NC}"
        fi
    fi
}

create_infrastructure() {
    print_header "CREATING INFRASTRUCTURE WITH TERRAFORM"

    cd "$TERRAFORM_DIR"

    print_step "Initializing Terraform..."
    terraform init
    print_success "Terraform initialized"

    print_step "Planning deployment..."
    terraform plan -out=tfplan

    print_step "Applying infrastructure (~20-25 minutes: EKS + node group + Jenkins EC2 + ECR, then ingress-nginx + kube-prometheus-stack + argocd + external-secrets)..."
    terraform apply tfplan
    print_success "Infrastructure created"

    CLUSTER_NAME=$(terraform output -raw eks_cluster_name 2>/dev/null || echo "task-manager")
    JENKINS_IP=$(terraform output -raw jenkins_public_ip 2>/dev/null)
    BACKEND_REPO=$(terraform output -raw backend_repository_url 2>/dev/null)
    FRONTEND_REPO=$(terraform output -raw frontend_repository_url 2>/dev/null)
    AWS_REGION_OUT=$(terraform output -raw aws_region 2>/dev/null || echo "us-east-1")
    GITHUB_REPO=$(terraform output -raw github_repo 2>/dev/null || echo "Ben-Sh7/aws-eks-cicd-pipeline")
    RDS_ENDPOINT=$(terraform output -raw rds_endpoint 2>/dev/null)
    RDS_SECRET=$(terraform output -raw rds_master_secret_name 2>/dev/null)

    cd "$PROJECT_DIR"
}

configure_kubectl() {
    print_header "CONFIGURING KUBECTL"

    print_step "Updating kubeconfig..."
    aws eks update-kubeconfig --region "${AWS_REGION_OUT:-us-east-1}" --name "${CLUSTER_NAME:-task-manager}"
    print_success "kubeconfig updated"

    print_step "Verifying cluster connection..."
    kubectl cluster-info
    print_success "kubectl connected to EKS cluster"
}

# The EC2's public IP changes every time create.sh recreates it, so the
# webhook payload URL would go stale every cycle without this - creates the
# webhook if none exists, or repoints an existing one at the new IP.
configure_github_webhook() {
    print_header "CONFIGURING GITHUB WEBHOOK"

    local hook_url="http://${JENKINS_IP}:8080/github-webhook/"
    local api="https://api.github.com/repos/${GITHUB_REPO}/hooks"
    local auth="Authorization: token $TF_VAR_github_pat"

    # Jenkins verifies GitHub's HMAC signature over the payload (configured by
    # the Groovy bootstrap), so the hook has to carry the same shared secret.
    local hook_secret_name hook_secret
    hook_secret_name=$(cd "$TERRAFORM_DIR" && terraform output -raw jenkins_webhook_secret_name 2>/dev/null || true)
    hook_secret=$(aws secretsmanager get-secret-value --secret-id "$hook_secret_name"         --query SecretString --output text 2>/dev/null || true)
    if [ -z "$hook_secret" ]; then
        print_error "Could not read the Jenkins webhook secret - GitHub deliveries would be rejected."
        exit 1
    fi

    # curl exits 0 on a 4xx, so each call is checked by status code instead - a
    # webhook that was never created is the difference between a pipeline that
    # works and one that silently never triggers.
    local list_response list_status existing_id write_status
    list_response=$(curl -s -w '
%{http_code}' -H "$auth" "$api")
    list_status=$(echo "$list_response" | tail -1)

    if [ "$list_status" != "200" ]; then
        print_error "Could not list the webhooks on $GITHUB_REPO (HTTP $list_status)."
        print_error "The PAT needs 'admin:repo_hook' and admin rights on that repo."
        exit 1
    fi

    # tr -d '\015' because jq.exe on Windows emits CRLF: a carriage return in the
    # id makes the URL below malformed, curl exits non-zero, and set -e takes
    # the script down with no message.
    existing_id=$(echo "$list_response" | sed '$d'         | jq -r '.[] | select(.config.url // "" | test("github-webhook")) | .id'         | tr -d '\015' | head -1)

    if [ -n "$existing_id" ] && [ "$existing_id" != "null" ]; then
        print_step "Updating existing webhook (id $existing_id) to point at $hook_url..."
        write_status=$(curl -s -o /dev/null -w '%{http_code}' -X PATCH -H "$auth" "$api/$existing_id"             -d "{\"config\":{\"url\":\"$hook_url\",\"content_type\":\"json\",\"secret\":\"$hook_secret\"}}" || echo "000")
        if [ "$write_status" != "200" ]; then
            print_error "Updating the webhook failed (HTTP $write_status)."
            exit 1
        fi
    else
        print_step "Creating webhook pointing at $hook_url..."
        write_status=$(curl -s -o /dev/null -w '%{http_code}' -X POST -H "$auth" "$api"             -d "{\"name\":\"web\",\"active\":true,\"events\":[\"push\"],\"config\":{\"url\":\"$hook_url\",\"content_type\":\"json\",\"secret\":\"$hook_secret\"}}")
        if [ "$write_status" != "201" ]; then
            print_error "Creating the webhook failed (HTTP $write_status)."
            exit 1
        fi
    fi
    print_success "GitHub webhook configured"

    configure_argocd_webhook
}

# Without this ArgoCD only notices a new image tag on its next 180s poll. The
# hook targets the one path published for it (see terraform/argocd-webhook.tf);
# a failure here is not fatal, it just leaves ArgoCD polling as before.
configure_argocd_webhook() {
    print_step "Registering the ArgoCD webhook so deploys skip its 3-minute poll..."

    local lb=""
    local i
    for i in $(seq 1 30); do
        lb=$(kubectl get svc -n ingress-nginx ingress-nginx-controller             -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)
        [ -n "$lb" ] && break
        sleep 10
    done

    if [ -z "$lb" ]; then
        echo -e "${YELLOW}WARNING: the ingress LoadBalancer has no hostname yet - skipping the ArgoCD webhook.${NC}"
        echo -e "${YELLOW}ArgoCD still syncs on its own poll; re-run create.sh to add the hook.${NC}"
        return 0
    fi

    local secret_name secret_value
    secret_name=$(cd "$TERRAFORM_DIR" && terraform output -raw argocd_webhook_secret_name 2>/dev/null || true)
    secret_value=$(aws secretsmanager get-secret-value --secret-id "$secret_name"         --query SecretString --output text 2>/dev/null || true)

    if [ -z "$secret_value" ]; then
        echo -e "${YELLOW}WARNING: could not read the ArgoCD webhook secret - skipping.${NC}"
        return 0
    fi

    local hook_url="http://${lb}/api/webhook"
    local api="https://api.github.com/repos/${GITHUB_REPO}/hooks"
    local auth="Authorization: token $TF_VAR_github_pat"

    local list_response existing_id write_status
    list_response=$(curl -s -H "$auth" "$api")
    existing_id=$(echo "$list_response"         | jq -r '.[] | select(.config.url // "" | test("/api/webhook")) | .id'         | tr -d '\015' | head -1)

    if [ -n "$existing_id" ] && [ "$existing_id" != "null" ]; then
        write_status=$(curl -s -o /dev/null -w '%{http_code}' -X PATCH -H "$auth" "$api/$existing_id"             -d "{\"config\":{\"url\":\"$hook_url\",\"content_type\":\"json\",\"secret\":\"$secret_value\"}}")
        [ "$write_status" = "200" ] || { echo -e "${YELLOW}WARNING: updating the ArgoCD webhook returned HTTP $write_status.${NC}"; return 0; }
    else
        write_status=$(curl -s -o /dev/null -w '%{http_code}' -X POST -H "$auth" "$api"             -d "{\"name\":\"web\",\"active\":true,\"events\":[\"push\"],\"config\":{\"url\":\"$hook_url\",\"content_type\":\"json\",\"secret\":\"$secret_value\"}}")
        [ "$write_status" = "201" ] || { echo -e "${YELLOW}WARNING: creating the ArgoCD webhook returned HTTP $write_status.${NC}"; return 0; }
    fi

    print_success "ArgoCD webhook configured ($hook_url)"
}

register_argocd_app() {
    print_header "REGISTERING APP WITH ARGOCD (GitOps bootstrap)"

    print_step "Waiting for the ArgoCD Application CRD to be available..."
    for i in $(seq 1 30); do
        if kubectl get crd applications.argoproj.io &> /dev/null; then
            break
        fi
        sleep 10
    done

    # The RDS endpoint, the name AWS generated for the RDS master secret, and
    # the ECR registry URLs (which embed the AWS account id) only exist after
    # apply and differ per deployment, so they can't live in git - they're
    # injected here as helm parameters instead.
    if [ -z "$RDS_ENDPOINT" ] || [ -z "$RDS_SECRET" ]; then
        print_error "Could not read the RDS outputs from Terraform - aborting before the app is registered."
        exit 1
    fi

    if [ -z "$BACKEND_REPO" ] || [ -z "$FRONTEND_REPO" ]; then
        print_error "Could not read the ECR outputs from Terraform - aborting before the app is registered."
        exit 1
    fi

    awk -v ep="$RDS_ENDPOINT" -v sec="$RDS_SECRET" -v be="$BACKEND_REPO" -v fe="$FRONTEND_REPO" '
        { print }
        /- values-images.yaml/ {
            print "      parameters:"
            print "        - name: config.dbHost"
            print "          value: \"" ep "\""
            print "        - name: secrets.awsSecretName"
            print "          value: \"" sec "\""
            print "        - name: backend.image.repository"
            print "          value: \"" be "\""
            print "        - name: frontend.image.repository"
            print "          value: \"" fe "\""
        }
    ' "$ARGOCD_APP" | kubectl apply -f -

    print_success "ArgoCD Application 'task-manager' registered (DB host: $RDS_ENDPOINT)"
    print_step "ArgoCD will now sync gitops/task-manager from git automatically (initial sync may take a minute)."
}

get_access_info() {
    print_header "🎉 DEPLOYMENT COMPLETE - ACCESS INFORMATION"

    echo -e "${GREEN}Infrastructure:${NC}"
    echo "  EKS Cluster: ${CLUSTER_NAME:-task-manager}"
    echo "  Region: ${AWS_REGION_OUT:-us-east-1}"

    if [ ! -z "$JENKINS_IP" ]; then
        echo -e "\n${GREEN}Jenkins (CI only - builds+pushes images, no cluster access):${NC}"
        echo "  URL: http://$JENKINS_IP:8080  (user: admin)"
        echo "  Password: $(cd "$TERRAFORM_DIR" && terraform output -raw jenkins_password_command 2>/dev/null; cd "$PROJECT_DIR")"
        echo "  The 'task-manager' Pipeline job and GitHub webhook are already configured."
    fi

    if [ ! -z "$BACKEND_REPO" ]; then
        echo -e "\n${GREEN}Docker Registries (ECR):${NC}"
        echo "  Backend: $BACKEND_REPO"
        echo "  Frontend: $FRONTEND_REPO"
    fi

    echo -e "\n${GREEN}Monitoring (Grafana - ClusterIP only, not public):${NC}"
    echo "  kubectl port-forward -n monitoring svc/kube-prometheus-stack-grafana 3000:80"
    echo "  Then open http://localhost:3000  (user: admin)"
    echo "  Password: aws secretsmanager get-secret-value --secret-id <see: terraform output grafana_access_instructions>"

    echo -e "\n${GREEN}CD (ArgoCD - ClusterIP only, not public):${NC}"
    echo "  kubectl port-forward -n argocd svc/argocd-server 8081:443"
    echo "  Then open https://localhost:8081  (user: admin, password:"
    echo "  kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)"

    echo -e "\n${GREEN}Ingress (app entrypoint):${NC}"
    echo "  kubectl get svc -n ingress-nginx ingress-nginx-controller   # find the external LoadBalancer hostname"

    echo -e "\n${GREEN}Kubernetes:${NC}"
    echo "  View pods: kubectl get pods"
    echo "  View logs: kubectl logs <pod-name>"
    echo "  View services: kubectl get svc"
    echo "  View ingress: kubectl get ingress"
    echo "  View ArgoCD sync status: kubectl get application -n argocd task-manager"

    if [ "$INFRA_ONLY" = true ]; then
        echo -e "\n${YELLOW}--infra-only was used: the app was NOT registered with ArgoCD.${NC}"
        echo "  Register it later with: kubectl apply -f gitops/argocd-application.yaml"
    fi

    echo -e "\n${GREEN}Database:${NC} RDS Postgres at ${RDS_ENDPOINT:-<pending>}"
    echo "  Credentials are generated and rotated by AWS in Secrets Manager, and pulled"
    echo "  into the cluster by external-secrets via IRSA - nothing to set up by hand."

    echo -e "\n${GREEN}When you're done:${NC}"
    echo "  ./destroy.sh"

    echo -e "\n${GREEN}Cost tracking:${NC}"
    echo "  This infrastructure costs ~\$139+/month if left running 24/7"
    echo "  For a few hours of testing: ~\$2-5"
}

main() {
    echo -e "${GREEN}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║     DEVOPS TASK MANAGER - COMPLETE PROJECT SETUP         ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"

    check_prerequisites
    create_infrastructure
    configure_kubectl
    configure_github_webhook

    if [ "$INFRA_ONLY" = false ]; then
        register_argocd_app
    fi

    get_access_info

    echo -e "\n${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}Project is ready! Start building! 🚀${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}\n"
}

main "$@"
