apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: task-manager
    {{- include "task-manager.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  BACKEND_URL: {{ .Values.config.backendUrl | quote }}
  PORT: {{ .Values.config.backendPort | quote }}
  {{- if .Values.config.dbSslCa }}
  DB_SSL_CA: {{ .Values.config.dbSslCa | quote }}
  {{- end }}
