# Passwords and shared secrets Terraform generates, and where each one is
# allowed to exist.
#
# Two different situations, handled two different ways:
#
# 1. A password only its consumer needs. Nothing in this configuration has to
#    know the value, so it is generated by an `ephemeral` resource and written
#    with `secret_string_wo` - a write-only argument. The value goes to AWS and
#    is never recorded in state or in a saved plan. Terraform cannot show it to
#    you afterwards, which is the point; AWS can.
#
# 2. A secret Terraform has to hand to two systems so they agree - the webhook
#    signing secrets, which GitHub uses to sign and the receiver uses to
#    verify. Terraform has to pass the same value to both sides as ordinary
#    resource arguments, and an ephemeral value is not allowed to reach those.
#    These stay in state, which is why the state bucket is encrypted,
#    versioned and access-controlled (backend.tf).
#
# That asymmetry is the honest shape of the problem: state holding secrets is
# managed, not eliminated.

# Bumping this rewrites every write-only secret below with a freshly generated
# value. Without a change here, an apply leaves them untouched - which is what
# makes write-only arguments stable rather than regenerating on every run.
#
# After bumping: Alertmanager and the app pick the new value up from External
# Secrets within the hour (or on pod restart); Jenkins applies its new admin
# password on its next boot.
variable "generated_secret_version" {
  description = "Rotation counter for the generated secrets written with write-only arguments (the JWT signing key, the Jenkins and Grafana admin passwords). Increment to rotate them; leaving it alone leaves them as they are."
  type        = number
  default     = 1
}

# ---------------------------------------------------------------------------
# Case 1: generated, written once, never read back by Terraform.
# ---------------------------------------------------------------------------

# Grafana reads this from a Kubernetes Secret that External Secrets fills
# (helm-addons.tf), not from a Helm value - a Helm value would put it back in
# state through the release resource, undoing the point of the write-only
# argument. Punctuation is excluded because the value travels through a
# templated YAML value on its way into the pod.
ephemeral "aws_secretsmanager_random_password" "grafana_admin" {
  password_length     = 32
  exclude_punctuation = true
}

resource "aws_secretsmanager_secret" "grafana_admin" {
  name_prefix             = "${local.project_name}/grafana-admin-"
  description             = "Grafana admin password (generated by Terraform, never stored in its state)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "grafana_admin" {
  secret_id = aws_secretsmanager_secret.grafana_admin.id

  # Written as JSON with both fields the Grafana chart expects, so External
  # Secrets can build the Kubernetes Secret out of two plain property lookups.
  # The alternative - one string plus a templated ExternalSecret - would need
  # Go-template syntax inside a Helm value that is itself passed through `tpl`,
  # and escaping braces twice to work around that is not worth a saved field.
  # The key names are the chart's own defaults (admin-user, admin-password).
  secret_string_wo = jsonencode({
    "admin-user"     = "admin"
    "admin-password" = ephemeral.aws_secretsmanager_random_password.grafana_admin.random_password
  })

  secret_string_wo_version = var.generated_secret_version
}

# Read by the Jenkins instance at boot with its own IAM role, and by you
# through the command in the jenkins_password_command output.
ephemeral "aws_secretsmanager_random_password" "jenkins_admin" {
  password_length     = 32
  exclude_punctuation = true
}

resource "aws_secretsmanager_secret" "jenkins_admin" {
  name_prefix             = "${local.project_name}/jenkins-admin-"
  description             = "Jenkins admin password (generated by Terraform, never stored in its state)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jenkins_admin" {
  secret_id                = aws_secretsmanager_secret.jenkins_admin.id
  secret_string_wo         = ephemeral.aws_secretsmanager_random_password.jenkins_admin.random_password
  secret_string_wo_version = var.generated_secret_version
}

# ---------------------------------------------------------------------------
# Case 2: two systems have to share the same value, so Terraform must hold it.
# ---------------------------------------------------------------------------

# Shared secret GitHub signs its Jenkins webhook payloads with. Terraform sets
# it on the GitHub webhook (github.tf) and Jenkins verifies against the copy it
# reads from Secrets Manager. Alphanumeric only: it travels through a JSON
# webhook configuration at GitHub and a Groovy string on the Jenkins side.
resource "random_password" "jenkins_webhook" {
  length  = 40
  special = false
}

resource "aws_secretsmanager_secret" "jenkins_webhook" {
  name_prefix             = "${local.project_name}/jenkins-webhook-"
  description             = "Shared secret GitHub signs Jenkins webhook payloads with (generated by Terraform)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jenkins_webhook" {
  secret_id     = aws_secretsmanager_secret.jenkins_webhook.id
  secret_string = random_password.jenkins_webhook.result
}
