# Generated rather than human-chosen. The character set is limited to what's
# safe inside the Groovy and shell templates these are rendered into, and
# recovery_window_in_days = 0 keeps destroy.sh from leaving billable secrets.

resource "random_password" "grafana_admin" {
  length           = 24
  special          = true
  override_special = "!#%&*()-_=+[]{}?"
}

resource "random_password" "jenkins_admin" {
  length           = 24
  special          = true
  override_special = "!#%&*()-_=+[]{}?"
}

# Shared secret GitHub signs its Jenkins webhook payloads with. Alphanumeric
# only: it travels through a JSON body in create.sh and a Groovy string here.
resource "random_password" "jenkins_webhook" {
  length  = 40
  special = false
}

resource "aws_secretsmanager_secret" "grafana_admin" {
  name_prefix             = "${local.project_name}/grafana-admin-"
  description             = "Grafana admin password (generated by Terraform)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "grafana_admin" {
  secret_id     = aws_secretsmanager_secret.grafana_admin.id
  secret_string = random_password.grafana_admin.result
}

resource "aws_secretsmanager_secret" "jenkins_admin" {
  name_prefix             = "${local.project_name}/jenkins-admin-"
  description             = "Jenkins admin password (generated by Terraform)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jenkins_admin" {
  secret_id     = aws_secretsmanager_secret.jenkins_admin.id
  secret_string = random_password.jenkins_admin.result
}

resource "aws_secretsmanager_secret" "jenkins_webhook" {
  name_prefix             = "${local.project_name}/jenkins-webhook-"
  description             = "Shared secret GitHub signs Jenkins webhook payloads with (generated by Terraform)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jenkins_webhook" {
  secret_id     = aws_secretsmanager_secret.jenkins_webhook.id
  secret_string = random_password.jenkins_webhook.result
}
