variable "generated_secret_version" {
  description = "Rotation counter for the generated secrets written with write-only arguments (the JWT signing key, the Jenkins and Grafana admin passwords). Increment to rotate them; leaving it alone leaves them as they are."
  type        = number
  default     = 1
}

ephemeral "aws_secretsmanager_random_password" "grafana_admin" {
  password_length     = 32
  exclude_punctuation = true
}

resource "aws_secretsmanager_secret" "grafana_admin" {
  name_prefix             = "${local.project_name}/grafana-admin-"
  description             = "Grafana admin password (generated by Terraform, never stored in its state)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "grafana_admin" {
  secret_id = aws_secretsmanager_secret.grafana_admin.id

  secret_string_wo = jsonencode({
    "admin-user"     = "admin"
    "admin-password" = ephemeral.aws_secretsmanager_random_password.grafana_admin.random_password
  })

  secret_string_wo_version = var.generated_secret_version
}

ephemeral "aws_secretsmanager_random_password" "jenkins_admin" {
  password_length     = 32
  exclude_punctuation = true
}

resource "aws_secretsmanager_secret" "jenkins_admin" {
  name_prefix             = "${local.project_name}/jenkins-admin-"
  description             = "Jenkins admin password (generated by Terraform, never stored in its state)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jenkins_admin" {
  secret_id                = aws_secretsmanager_secret.jenkins_admin.id
  secret_string_wo         = ephemeral.aws_secretsmanager_random_password.jenkins_admin.random_password
  secret_string_wo_version = var.generated_secret_version
}

resource "random_password" "jenkins_webhook" {
  length  = 40
  special = false
}

resource "aws_secretsmanager_secret" "jenkins_webhook" {
  name_prefix             = "${local.project_name}/jenkins-webhook-"
  description             = "Shared secret GitHub signs Jenkins webhook payloads with (generated by Terraform)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jenkins_webhook" {
  secret_id     = aws_secretsmanager_secret.jenkins_webhook.id
  secret_string = random_password.jenkins_webhook.result
}
