# Secrets the application itself needs.
#
# recovery_window_in_days = 0 so a teardown leaves nothing billing. External
# Secrets copies the value into the cluster (see irsa.tf).

# The key the backend signs its access tokens with (HS256). 64 characters is
# well above the 256 bits HS256 needs, and safe to carry in an environment
# variable.
#
# Generated and written without Terraform ever holding it: `ephemeral` produces
# the value during the apply and `secret_string_wo` is a write-only argument, so
# it reaches AWS and is not recorded in state or in a saved plan. Nothing here
# needs to read it back - the app gets it from External Secrets, and rotating it
# is a matter of incrementing generated_secret_version (admin-passwords.tf),
# which signs out every existing session by design.
ephemeral "aws_secretsmanager_random_password" "jwt_secret" {
  password_length     = 64
  exclude_punctuation = true
}

resource "aws_secretsmanager_secret" "jwt_secret" {
  name_prefix             = "${local.project_name}/jwt-secret-"
  description             = "Key the backend signs its access tokens with (generated by Terraform, never stored in its state)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id                = aws_secretsmanager_secret.jwt_secret.id
  secret_string_wo         = ephemeral.aws_secretsmanager_random_password.jwt_secret.random_password
  secret_string_wo_version = var.generated_secret_version
}

# The Slack URL, the Google client and the GitHub token used to live here, as
# Terraform-created entries seeded with placeholders. They are gone from this
# file on purpose: they are not this stack's secrets, they are yours. They now
# live in entries you create once by hand and Terraform only reads or
# references - see external-config.tf. The practical difference is that they
# survive `terraform destroy`, so a rebuild does not ask you to paste them
# again, and the GitHub token never reaches the state file at all.
