ephemeral "aws_secretsmanager_random_password" "jwt_secret" {
  password_length     = 64
  exclude_punctuation = true
}

resource "aws_secretsmanager_secret" "jwt_secret" {
  name_prefix             = "${local.project_name}/jwt-secret-"
  description             = "Key the backend signs its access tokens with (generated by Terraform, never stored in its state)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id                = aws_secretsmanager_secret.jwt_secret.id
  secret_string_wo         = ephemeral.aws_secretsmanager_random_password.jwt_secret.random_password
  secret_string_wo_version = var.generated_secret_version
}

