# Secrets the application itself needs. Generated rather than chosen, like
# admin-passwords.tf, and stored under the "task-manager/" prefix that
# destroy.sh checks. recovery_window_in_days = 0 so a teardown leaves nothing
# billing. External Secrets copies the value into the cluster (see irsa.tf).

# The key the backend signs its access tokens with (HS256). 64 random
# alphanumeric characters is ~380 bits of entropy - well above the 256 bits
# HS256 needs - and safe to carry in an environment variable.
resource "random_password" "jwt_secret" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "jwt_secret" {
  name_prefix             = "${local.project_name}/jwt-secret-"
  description             = "Key the backend signs its access tokens with (generated by Terraform)"
  recovery_window_in_days = 0
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = random_password.jwt_secret.result
}
