resource "random_password" "argocd_webhook" {
  length  = 40
  special = false
}

resource "aws_secretsmanager_secret" "argocd_webhook" {
  name_prefix             = "${local.project_name}/argocd-webhook-"
  description             = "Shared secret GitHub signs ArgoCD webhook payloads with (generated by Terraform)"
  recovery_window_in_days = 0

  tags = merge(
    local.common_tags,
    { Name = "${local.project_name}-argocd-webhook-secret" }
  )
}

resource "aws_secretsmanager_secret_version" "argocd_webhook" {
  secret_id     = aws_secretsmanager_secret.argocd_webhook.id
  secret_string = random_password.argocd_webhook.result
}

resource "kubernetes_ingress_v1" "argocd_webhook" {
  metadata {
    name      = "argocd-webhook"
    namespace = "argocd"
    annotations = {
      "nginx.ingress.kubernetes.io/backend-protocol" = "HTTPS"
    }
    labels = {
      "app.kubernetes.io/part-of"    = "argocd"
      "app.kubernetes.io/managed-by" = "terraform"
    }
  }

  spec {
    ingress_class_name = "nginx"

    rule {
      host = local.argocd_fqdn

      http {
        path {
          path      = "/api/webhook"
          path_type = "Exact"

          backend {
            service {
              name = "argocd-server"
              port {
                number = 443
              }
            }
          }
        }
      }
    }
  }

  depends_on = [helm_release.argocd, helm_release.ingress_nginx]
}
