# ArgoCD polls git every 180s (timeout.reconciliation), so a deploy sits idle
# for up to three minutes after CI pushes the new image tag. A GitHub webhook
# collapses that to seconds.
#
# The catch is that receiving a webhook means exposing the ArgoCD API server,
# which is deliberately ClusterIP. So exactly one path is published - the
# ingress below uses pathType Exact, which matches /api/webhook and nothing
# else: not the UI, not /api/v1, not the gRPC endpoint. Those stay reachable
# only through kubectl port-forward, as before.

resource "random_password" "argocd_webhook" {
  length  = 40
  special = false
}

resource "aws_secretsmanager_secret" "argocd_webhook" {
  name_prefix             = "${local.project_name}/argocd-webhook-"
  description             = "Shared secret GitHub signs ArgoCD webhook payloads with (generated by Terraform)"
  recovery_window_in_days = 0

  tags = merge(
    local.common_tags,
    { Name = "${local.project_name}-argocd-webhook-secret" }
  )
}

resource "aws_secretsmanager_secret_version" "argocd_webhook" {
  secret_id     = aws_secretsmanager_secret.argocd_webhook.id
  secret_string = random_password.argocd_webhook.result
}

# Payloads that are not signed with the secret above are rejected by ArgoCD, so
# the open path cannot be used to force syncs.
resource "kubernetes_ingress_v1" "argocd_webhook" {
  metadata {
    name      = "argocd-webhook"
    namespace = "argocd"
    annotations = {
      # argocd-server keeps its own TLS; nginx talks HTTPS to it rather than the
      # alternative of running the server with --insecure just to serve one path.
      "nginx.ingress.kubernetes.io/backend-protocol" = "HTTPS"
    }
    labels = {
      "app.kubernetes.io/part-of"    = "argocd"
      "app.kubernetes.io/managed-by" = "terraform"
    }
  }

  spec {
    ingress_class_name = "nginx"

    rule {
      http {
        path {
          path      = "/api/webhook"
          path_type = "Exact"

          backend {
            service {
              name = "argocd-server"
              port {
                number = 443
              }
            }
          }
        }
      }
    }
  }

  depends_on = [helm_release.argocd, helm_release.ingress_nginx]
}
