apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: task-manager
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: tasksdb
  BACKEND_URL: http://backend-service:3001
  PORT: "3001"
