backend:
  image:
    repository: 619648596437.dkr.ecr.us-east-1.amazonaws.com/devops-task-manager-backend
    tag: "4bacd7c"

frontend:
  image:
    repository: 619648596437.dkr.ecr.us-east-1.amazonaws.com/devops-task-manager-frontend
    tag: "4bacd7c"
